vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename, { desc = "重命名符号 (Rename)" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "代码操作 (Code Action)" })
vim.keymap.set("n", "<leader>cd", vim.diagnostic.open_float, { desc = "显示悬浮诊断 (Diagnostic)" })
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({ async = true, lsp_fallback = true })
end, { desc = "格式化缓冲区 (Format)" })
vim.keymap.set("n", "gd", "<cmd>Telescope lsp_definitions<cr>", { desc = "跳转到定义" })
vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "跳转到声明" })
vim.keymap.set("n", "gri", "<cmd>Telescope lsp_implementations<cr>", { desc = "跳转到实现" })
vim.keymap.set("n", "grr", "<cmd>Telescope lsp_references<cr>", { desc = "查看所有引用" })
vim.keymap.set("n", "grt", "<cmd>Telescope lsp_type_definitions<cr>", { desc = "查看类型定义" })
vim.keymap.set("n", "gO", vim.lsp.buf.document_symbol, { desc = "查看文档符号" })
vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "悬浮显示文档/注释" })
vim.keymap.set("n", "gra", vim.lsp.buf.code_action, { desc = "代码操作" })
vim.keymap.set("n", "grn", vim.lsp.buf.rename, { desc = "重命名" })
