vim.keymap.set({ "n", "x" }, "<A-up>", function()
	require("multicursor-nvim").lineAddCursor(-1)
end, { desc = "在上方添加光标" })
vim.keymap.set({ "n", "x" }, "<A-down>", function()
	require("multicursor-nvim").lineAddCursor(1)
end, { desc = "在下方添加光标" })
vim.keymap.set({ "n", "x" }, "<A-S-up>", function()
	require("multicursor-nvim").lineSkipCursor(-1)
end, { desc = "跳过上方行" })
vim.keymap.set({ "n", "x" }, "<A-S-down>", function()
	require("multicursor-nvim").lineSkipCursor(1)
end, { desc = "跳过下方行" })

vim.keymap.set({ "n", "x" }, "<A-n>", function()
	require("multicursor-nvim").matchAddCursor(1)
end, { desc = "匹配添加光标（下一个）" })

vim.keymap.set({ "n", "x" }, "<A-s>", function()
	require("multicursor-nvim").matchSkipCursor(1)
end, { desc = "跳过匹配（下一个）" })

vim.keymap.set({ "n", "x" }, "<A-N>", function()
	require("multicursor-nvim").matchAddCursor(-1)
end, { desc = "匹配添加光标（上一个）" })

vim.keymap.set({ "n", "x" }, "<A-S>", function()
	require("multicursor-nvim").matchSkipCursor(-1)
end, { desc = "跳过匹配（上一个）" })

vim.keymap.set("n", "<C-leftmouse>", function(...)
	require("multicursor-nvim").handleMouse(...)
end, { desc = "鼠标添加光标" })
vim.keymap.set("n", "<C-leftdrag>", function(...)
	require("multicursor-nvim").handleMouseDrag(...)
end, { desc = "鼠标拖动" })
vim.keymap.set("n", "<C-leftrelease>", function(...)
	require("multicursor-nvim").handleMouseRelease(...)
end, { desc = "鼠标释放" })
