-- 【DAP 调试 (Debug)】
vim.keymap.set("n", "<F5>", function()
	require("dap").continue()
end, { desc = "启动/继续调试" })
vim.keymap.set("n", "<F6>", function()
	require("dap").disconnect({ terminateDebuggee = true })
end, { desc = "断开调试" })
vim.keymap.set("n", "<F10>", function()
	require("dap").step_over()
end, { desc = "逐过程 (Step Over)" })
vim.keymap.set("n", "<F11>", function()
	require("dap").step_into()
end, { desc = "单步调试 (Step Into)" })
vim.keymap.set("n", "<F12>", function()
	require("dap").step_out()
end, { desc = "单步跳出 (Step Out)" })
vim.keymap.set("n", "<leader>dc", function()
	require("dap").continue()
end, { desc = "启动/继续调试" })
vim.keymap.set("n", "<leader>ds", function()
	require("dap").disconnect({ terminateDebuggee = true })
end, { desc = "断开调试" })
vim.keymap.set("n", "<leader>dv", function()
	require("dap").step_over()
end, { desc = "逐过程 (Step Over)" })
vim.keymap.set("n", "<leader>di", function()
	require("dap").step_into()
end, { desc = "单步调试 (Step Into)" })
vim.keymap.set("n", "<leader>do", function()
	require("dap").step_out()
end, { desc = "单步跳出 (Step Out)" })

vim.keymap.set("n", "<leader>dp", function()
	require("dap").toggle_breakpoint()
end, { desc = "切换断点" })

vim.keymap.set("n", "<F9>", function()
	require("dap").toggle_breakpoint()
end, { desc = "切换断点" })

vim.keymap.set("n", "<leader>dt", function()
	require("dapui").toggle()
end, { desc = "显示/隐藏调试 UI" })
